import * as XLSX from 'xlsx';

export interface StudentMarkSheetSubject {
  subjectName: string;
  subjectCode?: string;
  ct1: number | string;
  ct2: number | string;
  ct3: number | string;
  total: number | string;
  maxTotal?: number | string;
  status: string;
}

export interface StudentMarkSheetRecord {
  studentId: string;
  studentName: string;
  registerNumber: string;
  campusName: string;
  campusCode?: string;
  academicYear: string;
  semesterNumber: number;
  semesterText: string;
  sgpa: number | string;
  cgpa: number | string;
  status: string;
  submittedDate?: string;
  subjects: StudentMarkSheetSubject[];
}

export interface ExportMetadata {
  academicYear?: string;
  semesterText?: string;
  campusText?: string;
  generatedDate?: string;
  generatedBy?: string;
}

/**
 * Escapes a field value for CSV compliance (RFC 4180).
 */
function escapeCsv(value: any): string {
  if (value === null || value === undefined) return '';
  const str = String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

/**
 * Generates and triggers download of an official Excel (.xlsx) Academic Mark Sheet.
 * Applies vertical cell merging across subject rows for each student.
 */
export function generateAcademicExcel(
  records: StudentMarkSheetRecord[],
  metadata: ExportMetadata,
  filename: string
): void {
  if (!records || records.length === 0) {
    throw new Error('No academic records available for the selected filters.');
  }

  // Build 2D rows array
  const rows: any[][] = [];

  // Row 0: Main Title
  rows.push(['PTF Vizhuthugal']);
  // Row 1: Subtitle
  rows.push(['Student Academic Mark Sheet']);

  // Rows 2-4: Institutional Metadata Block
  rows.push([
    'Academic Year:',
    metadata.academicYear || 'All Academic Years',
    '',
    'Generated Date:',
    metadata.generatedDate || new Date().toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata' }),
  ]);
  rows.push([
    'Semester:',
    metadata.semesterText || 'All Semesters',
    '',
    'Generated By:',
    metadata.generatedBy || 'Institutional Administrator',
  ]);
  rows.push(['Campus:', metadata.campusText || 'All Authorized Campuses']);

  // Row 5: Blank separator
  rows.push([]);

  // Row 6: Column Headers (13 columns)
  const headers = [
    'Student Name',
    'Registration No',
    'Campus',
    'Academic Year',
    'Semester',
    'Subject',
    'CT1',
    'CT2',
    'CT3',
    'Total',
    'SGPA',
    'CGPA',
    'Status',
  ];
  rows.push(headers);

  // Merges array
  const merges: XLSX.Range[] = [
    // Merge title row
    { s: { r: 0, c: 0 }, e: { r: 0, c: headers.length - 1 } },
    // Merge subtitle row
    { s: { r: 1, c: 0 }, e: { r: 1, c: headers.length - 1 } },
  ];

  let currentRow = rows.length;

  // Group and format records by student
  records.forEach((student) => {
    const studentSubjects = student.subjects.length > 0
      ? student.subjects
      : [
          {
            subjectName: 'No subjects recorded',
            subjectCode: '',
            ct1: '—',
            ct2: '—',
            ct3: '—',
            total: '—',
            status: student.status || 'PENDING',
          },
        ];

    const studentStartRow = currentRow;
    const numRows = studentSubjects.length;

    studentSubjects.forEach((sub) => {
      rows.push([
        student.studentName,
        student.registerNumber,
        student.campusName,
        student.academicYear,
        student.semesterText,
        sub.subjectCode ? `${sub.subjectName} (${sub.subjectCode})` : sub.subjectName,
        sub.ct1,
        sub.ct2,
        sub.ct3,
        sub.total,
        student.sgpa,
        student.cgpa,
        sub.status || student.status,
      ]);
      currentRow++;
    });

    // If student has multiple subjects, merge student-level columns vertically
    if (numRows > 1) {
      const studentEndRow = studentStartRow + numRows - 1;
      // Col 0: Student Name
      merges.push({ s: { r: studentStartRow, c: 0 }, e: { r: studentEndRow, c: 0 } });
      // Col 1: Registration No
      merges.push({ s: { r: studentStartRow, c: 1 }, e: { r: studentEndRow, c: 1 } });
      // Col 2: Campus
      merges.push({ s: { r: studentStartRow, c: 2 }, e: { r: studentEndRow, c: 2 } });
      // Col 3: Academic Year
      merges.push({ s: { r: studentStartRow, c: 3 }, e: { r: studentEndRow, c: 3 } });
      // Col 4: Semester
      merges.push({ s: { r: studentStartRow, c: 4 }, e: { r: studentEndRow, c: 4 } });
      // Col 10: SGPA
      merges.push({ s: { r: studentStartRow, c: 10 }, e: { r: studentEndRow, c: 10 } });
      // Col 11: CGPA
      merges.push({ s: { r: studentStartRow, c: 11 }, e: { r: studentEndRow, c: 11 } });
      // Col 12: Status
      merges.push({ s: { r: studentStartRow, c: 12 }, e: { r: studentEndRow, c: 12 } });
    }
  });

  // Create sheet from array of arrays
  const ws = XLSX.utils.aoa_to_sheet(rows);

  // Apply merges
  ws['!merges'] = merges;

  // Set professional column widths
  ws['!cols'] = [
    { wch: 24 }, // Student Name
    { wch: 18 }, // Registration No
    { wch: 22 }, // Campus
    { wch: 15 }, // Academic Year
    { wch: 14 }, // Semester
    { wch: 28 }, // Subject
    { wch: 10 }, // CT1
    { wch: 10 }, // CT2
    { wch: 10 }, // CT3
    { wch: 12 }, // Total
    { wch: 10 }, // SGPA
    { wch: 10 }, // CGPA
    { wch: 14 }, // Status
  ];

  // Create workbook
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Academic Mark Sheet');

  // Trigger download
  XLSX.writeFile(wb, filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`);
}

/**
 * Generates and triggers download of a flat normalized CSV (.csv) Academic Mark Sheet.
 * Repeats student-level fields on each subject row (RFC 4180 + UTF-8 BOM).
 */
export function generateAcademicCSV(
  records: StudentMarkSheetRecord[],
  _metadata: ExportMetadata,
  filename: string
): void {
  if (!records || records.length === 0) {
    throw new Error('No academic records available for the selected filters.');
  }

  const headers = [
    'Student Name',
    'Registration No',
    'Campus',
    'Academic Year',
    'Semester',
    'Subject',
    'CT1',
    'CT2',
    'CT3',
    'Total',
    'SGPA',
    'CGPA',
    'Status',
  ];

  const csvRows: string[] = [headers.map(escapeCsv).join(',')];

  records.forEach((student) => {
    const studentSubjects = student.subjects.length > 0
      ? student.subjects
      : [
          {
            subjectName: 'No subjects recorded',
            subjectCode: '',
            ct1: '—',
            ct2: '—',
            ct3: '—',
            total: '—',
            status: student.status || 'PENDING',
          },
        ];

    studentSubjects.forEach((sub) => {
      const row = [
        student.studentName,
        student.registerNumber,
        student.campusName,
        student.academicYear,
        student.semesterText,
        sub.subjectCode ? `${sub.subjectName} (${sub.subjectCode})` : sub.subjectName,
        sub.ct1,
        sub.ct2,
        sub.ct3,
        sub.total,
        student.sgpa,
        student.cgpa,
        sub.status || student.status,
      ];
      csvRows.push(row.map(escapeCsv).join(','));
    });
  });

  // Prepend UTF-8 BOM (\uFEFF) so Excel opens CSV without encoding issues
  const csvContent = '\uFEFF' + csvRows.join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename.endsWith('.csv') ? filename : `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Builds a sanitized filename based on student name / campus, semester, and academic year.
 */
export function buildExportFilename(
  type: 'single' | 'bulk',
  format: 'xlsx' | 'csv',
  details: {
    studentName?: string;
    campusCode?: string;
    semesterNumber?: number | string;
    academicYear?: string;
  }
): string {
  const sanitize = (s?: string) => (s ? s.replace(/[^a-zA-Z0-9_-]/g, '_') : 'All');
  const semTag = details.semesterNumber ? `Sem${details.semesterNumber}` : 'AllSem';
  const yearTag = details.academicYear ? sanitize(details.academicYear) : '2026-27';

  let namePart = '';
  if (type === 'single' && details.studentName) {
    namePart = sanitize(details.studentName);
  } else {
    namePart = details.campusCode ? sanitize(details.campusCode) : 'All_Campuses';
  }

  return `PTF_Vizhuthugal_${namePart}_${semTag}_${yearTag}.${format}`;
}
